# Generated by Django 2.0.2 on 2018-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kafedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prepodavateli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya', models.CharField(max_length=200)),
                ('login', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('kafedra', models.ManyToManyField(help_text='  ', to='catalog.kafedra')),
            ],
        ),
    ]
